GET http://localhost:8888/testUsers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjp7Im5hbWUiOiJPWUFNQUIiLCJwYXNzd29yZCI6IiQyYiQxMCRnbVdDdVN1c1dqLmFLd0ZlZFJhQnh1UUxvYVRQNURLZW1tdmJxRWc4TmhHQ05RUEU5dHhSMiJ9LCJpYXQiOjE3NDY2Nzg2MjZ9.tiPuT8ZCIdyZYiBVtdLqXEgIwzusHXEARQ9fWIFTsR4
###
POST http://localhost:8888/newUser
Content-Type: application/json

{
    "name":"OYAMAB",
    "password":"yamz"
}

###
POST http://localhost:8888/login
Content-Type: application/json

{
    "name":"OYAMAB",
    "password":"yamz"
}