GET http://localhost:8888/testUsers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjp7Im5hbWUiOiJPWUFNQUIiLCJwYXNzd29yZCI6IiQyYiQxMCQ0SWo4SHdzc255V0I4anV5d0Nua0Z1U1haZW1wTEN6UzRXSDU2Z1lOZklSd1QwaWwyWHkwaSJ9LCJpYXQiOjE3NDY3NjEyMjV9.avHrx7OC-OMA-9-gfisnkREmAyczoB-MXBKlLMzBxd0
###
POST http://localhost:8888/newUser
Content-Type: application/json

{
    "name":"OYAMAB",
    "password":"yamz"
}

###
POST http://localhost:8888/login
Content-Type: application/json

{
    "name":"OYAMAB",
    "password":"yamz"
}